# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='读者姓名')),
                ('email', models.CharField(max_length=30, verbose_name='读者邮箱')),
                ('subject', models.CharField(max_length=30, verbose_name='读者反馈主题')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': '读者意见',
                'verbose_name': '读者意见',
            },
        ),
    ]
