# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160926_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='图片名称'),
        ),
    ]
