# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160926_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='链接地址'),
        ),
    ]
